### ISSUE TITLE
Can this be upgraded to support tensorflow v2?

### ISSUE THREAD

**Issue by bob-hinrichs** [surajitsaikia27/Vector_robot_ObjectDetection#1]
I would love to try this out, however I came across these issues:
tensorflow is in v2 now and does not support the code. I tried to get around it by implementing compatibility mode as such in detect_odr.py: f = tf.compat.v1.gfile.FastGFile(frozen_pb_file, 'rb')
graph_def = tf.compat.v1.GraphDef()
However, also, it could not find the file frozen_inference_graph.pb. I don't see evidence of this file.

**Comment by surajitsaikia27** [comment]
Hi..I just realized there was a mistake with regards to the model path in a file. I have modified that in the repository, or you can directly change it in the file 'detect_odr.py ' inside the model directory.
At line 53, you can set  model_path = "./data" or to the path where you have downloaded the model.

Sorry for this inconvenience. Let me know if it worked.

**Comment by bob-hinrichs** [comment]
I appreciate your work on this and addressing the issue!  Thank you.  I think it would help people to describe or reference, where frozen_inference_graph.pb comes from, as it is not in your project and when one follows the steps in the blog post, the program fails because of this missing step?  I am new to this and I am having a very difficult time figuring out where that comes from.

**Comment by surajitsaikia27** [comment]
I provide a link in the Github:
To run this module, please clone this repository and download the pre-trained model from here, [url](https://drive.google.com/file/d/113-3Kud0Ner2NR4ZiSOnQUOq5C4G16CC/view?usp=sharing,). Next, put the downloaded model inside the data folder.

Let me know if you can download it now.
bdw, which tensorflow version you are using? This format will not work in Tensorflow 2.0.

**Comment by bob-hinrichs** [comment]
Ok, I was going to see if using the 'compat.v1' classes noted above would allow this to run in tensorflow v2.  However, that was not enough.  To get this working I had to run pip3 install tensorflow==1.13.2, since v2 is the default install.  Also I see you say v1.12 is required, however, this package appears to no longer be available.  I have gotten the program running, thank you! He can recognize a few things (kitchen appliance, person, face).  One thing I note is that the robot's head is sometimes tilted downward, so might want to lift the head before taking the photo.  Also I notice that lighting can be an issue, I am not sure if anything can be done about that though.  Thanks again!

**Comment by surajitsaikia27** [comment]
Great to hear that. This is my first program in this robot which I tried immediately after buying, so it needs much work.
You can tilt the robot by using:
robot.behavior.set_lift_height(0.0)
